#!/bin/bash

source /etc/jelastic/environment

old_password=`cat /etc/powerdns/pdns.conf|grep gmysql-password=|sed 's/gmysql-password=//g'`;
mysqlpass=`< /dev/urandom tr -dc A-Za-z0-9 | head -c32`;
mysqladmin -u root -h localhost -p$old_password password $mysqlpass;
sed -i '/'gmysql-password='/d' $CARTRIDGE_HOME/versions/$Version/config/pdns.conf;
sed -i "/gmysql-user=root/a gmysql-password=$mysqlpass" $CARTRIDGE_HOME/versions/$Version/config/pdns.conf;
sed -i '/'db_pass'/d' $CARTRIDGE_HOME/versions/$Version/poweradmin/inc/config.inc.php;
sed -i "/db_user		= 'root'/a \$db_pass  = \'$mysqlpass\';" $CARTRIDGE_HOME/versions/$Version/poweradmin/inc/config.inc.php;
